### ISSUE TITLE
Switch NuGet package to NetStandard 1.1 (or 1.2)

### ISSUE THREAD

**Issue by MichaelKetting** [Microsoft/cci#2]
I've noticed that the latest NuGet packages (https://www.nuget.org/packages/Microsoft.Cci/4.0.0-rc3-24214-00 and https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.Cci/4.0.0-rc4-24220-00) use NetStandard 1.3 (i.e. .NET 4.6) as minimum requirement while the project on GitHub still only requires .NET 4.0. Please publish a new version with a reduced version requirement since it appears that .NET 4.6 is not actually needed and significantly limits the use of Microsoft.Cci. Personally, I'll have to repackage the assembly and host it on my own to get around this issue. 

I'd love to send a PR that fixes this, but it looks like there's no nuspec file where this could be configured uploaded on GitHub.

**Comment by nguerrera** [comment]
Once #12 is merged, you should be able to make changes code changes to go down to 1.2. Code changes are needed, it is not just a nuspec change.

**Comment by MichaelKetting** [comment]
Thanks for the update. I've since come to realize that the missing GAC is actually a much greater hurdle to using NetStandard so I had to recompile it anyway against the full framework.

**Comment by nguerrera** [comment]
In that case I'll close this.
