### ISSUE TITLE
How should resource-emitting code be translated?

### ISSUE THREAD

**Issue by masonwheeler** [Microsoft/cci#23]
I'm working on porting a compiler over from Reflection.Emit to CCI.  I've got most of it figured out by this point, but I can't seem to wrap my head around the Resource class.

The CLR managed resource model defines a Resource as a thing with a name that's a key to a list of name-value pairs.  You call [`ModuleBuilder.DefineResource()`](https://msdn.microsoft.com/en-us/library/s3y2e90h(v=vs.110).aspx), passing a Name and Description, to get an `IResourceWriter`, and then call [`AddResource`](https://msdn.microsoft.com/en-us/library/system.resources.iresourcewriter.addresource(v=vs.110).aspx) 1 or more times, passing a Name for each individual resource within that `IResourceWriter`'s named group.

The `Microsoft.Cci.MutableCodeModel.Resource` class appears to correspond to the individual sub-resources written by `IResourceWriter`, as it has a Name and a byte array for contents but no Description or collection of name-value pairs for sub-resources, but it also appears to correspond to the outer-level resource group, as it can refer to an external resource file, which can contain the name-value pairs within it.  It's all very unclear as to what the correct way is to port code using the Reflection.Emit model.

What is the idiomatic way to create managed resource groups with CCI?

**Comment by MichalStrehovsky** [comment]
`Microsoft.Cci.MutableCodeModel.Resource` actually corresponds to `ModuleBuilder.DefineManifestResource`.

`ModuleBuilder.DefineResource` is just a shortcut for creating a [ResourceWriter](https://msdn.microsoft.com/en-us/library/system.resources.resourcewriter(v=vs.110).aspx), saving it to a stream, and calling `DefineManifestResource` with the given name and stream.

Don't worry about the `description` parameter. That one is unceremoniously [dropped on the floor](https://github.com/dotnet/coreclr/blob/204f6e8859e3676114c85f49b8d2c311458ac715/src/mscorlib/src/System/Reflection/Emit/ModuleBuilder.cs#L1266]) and ignored.

**Comment by masonwheeler** [comment]
Thanks for the clarification.  So I just provide my own wrapper around `ResourceWriter` to the facilities in the compiler that's expecting it, and when they close it I create a `Resource` with the byte stream that it's produced?

**Comment by MichalStrehovsky** [comment]
> So I just provide my own wrapper around `ResourceWriter` to the facilities in the compiler that's expecting it, and when they close it I create a `Resource` with the byte stream that it's produced?

I would try it out first in a small scratch program, but that's how it should work, yes. `ResourceWriter` conveniently implements `IResourceWriter`, so maybe you don't even need much wrapping.

**Comment by masonwheeler** [comment]
Thanks.  I was able to get it working now.
