### ISSUE TITLE
Call is being emitted to the wrong method

### ISSUE THREAD

**Issue by masonwheeler** [microsoft/cci#24]
I'm having a bizarre problem that I can't track down: when `Main` calls a certain method, everything in the emitting code looks right, but in the generated IL it's a call back to Main instead of to the method I'm trying to call.  Or at least, that's what ILDasm says.  PEVerify says

> [IL]: Error: [C:\Users\Mason\AppData\Local\Temp\msbuild\testcase.exe : Array_polymorphic_foreachModule::Main] Method does not exist.

It's not clear whether that's referring to the method being called or the method in which the error occurs.

Do you have any idea how I could track down what's going wrong?  At the point where I emit the call, it's passing the correct `IMethodReference` to `_il.Emit()`, and the target method does get generated and shows up as expected in ILDasm, so I'm kind of stuck here.

**Comment by masonwheeler** [comment]
In case you need to reproduce the issue to see what's going on, you can find the compiler at

https://github.com/boo-lang/boo/tree/CCI-conversion

Open the src/Boo-VS2010.sln project in Visual Studio, build it, (you may need to adjust the references to the CCI assemblies to match your local system,) run the "Array_polymorphic_foreach" test from the test suite, and have a look at the generated EXE.

**Comment by masonwheeler** [comment]
Found the problem.  The methods were being created with no `InternTable`, and so instead of raising an error, it had a DummyInternTable that failed silently.  This should be considered a bug, since it can cause hard-to-debug errors further down the line!

**Comment by MichalStrehovsky** [comment]
Changing this behavior would be a breaking change. CCI is no longer in active development and as the `README.md` for this repo says, we suggest to use alternatives to CCI for new projects.

**Comment by masonwheeler** [comment]
Yes, I saw that.  But the suggested alternatives all appear to be focused on other things.  Cecil is for loading existing assemblies and rewriting them; `System.Reflection.Metadata` is a metadata *reader*, and Roslyn is a compiler in its own right, but the project I have is an existing, mature compiler with its own established architecture that's very different from how Roslyn does things.

What I need is a more powerful codegen than Reflection.Emit, and CCI is the only one that looks suitable as a code generation backend for an existing compiler.

**Comment by MichalStrehovsky** [comment]
>  Cecil is for loading existing assemblies and rewriting them

You can create assemblies from scratch [with Cecil](http://stackoverflow.com/questions/39366963/how-to-use-mono-cecil-to-create-helloworld-exe).

CCI and Cecil are very similar (both build an object model of the metadata and IL and let you do stuff with it). Whether the object model is created from an assembly on disk, or by explicitly newing up classes doesn't matter to CCI or Cecil.

In the .NET Native team at Microsoft we actually exclusively use CCI for it's rewriting capabilities.
